In [1]:
import numpy as np
x= np.array([1.5, 2.2, 1.56, 1.78, 1.82, 1.90, 1.66, 1.91, 1.76, 1.88])
np.mean(x)
np.sum(x)
np.std(x)
x= ([0.56744433976086,  0.6871979493457484, 0.8463706897561651, 0.31110389619407564, 0.23511891089708503, 0.6577102252485975, 0.6648803069356928, 0.49989209380778477, 0.023793000481246773, 0.8777416618364761, 0.45262683262543646, 0.6430419554811486, 0.06347145550399458, 0.10628535246898096, 0.13551828266629173, 0.7030802149078524, 0.8656176079542628, 0.3939640454664668, 0.5144582885753547, 0.6255032779041944])
np.sum(x)
np.mean(x)
np.median(x)
np.std(x)
x= np.array([0.56744433976086,  0.6871979493457484, 0.8463706897561651, 0.31110389619407564, 0.23511891089708503, 0.6577102252485975, 0.6648803069356928, 0.49989209380778477, 0.023793000481246773, 0.8777416618364761, 0.45262683262543646, 0.6430419554811486, 0.06347145550399458, 0.10628535246898096, 0.13551828266629173, 0.7030802149078524, 0.8656176079542628, 0.3939640454664668, 0.5144582885753547, 0.6255032779041944]).reshape(5,4)
print(x)
x= ([0.68719795, 0.65771023, 0.87774166, 0.10628535, 0.39396405])
np.median(x)
x= ([0.023793, 0.87774166, 0.45262683, 0.64304196])
np.mean(x)
x= ([0.56744434, 0.23511891, 0.023793, 0.06347146, 0.86561761],[0.68719795, 0.65771023, 0.87774166, 0.10628535, 0.39396405],[0.84637069, 0.66488031, 0.45262683, 0.13551828, 0.51445829])
np.std(x)

[[0.56744434 0.68719795 0.84637069 0.3111039 ]
 [0.23511891 0.65771023 0.66488031 0.49989209]
 [0.023793   0.87774166 0.45262683 0.64304196]
 [0.06347146 0.10628535 0.13551828 0.70308021]
 [0.86561761 0.39396405 0.51445829 0.62550328]]


0.2905108162888491